import { Hono } from 'hono';
import { google } from 'googleapis';
import { container } from 'tsyringe';
import { and, eq } from 'drizzle-orm';
import type { Database } from '@crm/database';
import { GMAIL_SCOPE_URLS } from '@crm/shared';
import { auth } from '../auth/better-auth';
import { IntegrationService } from '../integrations/service';
import { users } from '../users/schema';
import { logger } from '../utils/logger';
import { internalFetch } from '../utils/internal-fetch';
import { getEnv } from '../env';
import { signOAuthState, verifyOAuthState, OAUTH_STATE_TTL_SECONDS } from './state';

const app = new Hono();

interface OAuthCredentials {
  clientId: string;
  clientSecret: string;
  source: 'integration' | 'environment';
}

/**
 * Resolve the OAuth client credentials for a tenant.
 *
 * `/authorize` and `/callback` MUST agree on these — Google validates the
 * client_id/redirect_uri pair at both ends — and they no longer have a shared
 * in-process store to pass them through, so they call this instead of each
 * resolving credentials in its own way.
 *
 * The client secret used to be accepted as a query parameter and stashed in the
 * state store for the callback to pick up. That is gone: a secret in a URL is a
 * secret in the Cloud Run request log, and nothing calls it — the web app sends
 * only tenantId and userId (apps/web/components/integrations/gmail-card.tsx).
 * First-time setup uses GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET, which are
 * required env vars on every crm-api instance.
 */
async function resolveOAuthCredentials(tenantId: string): Promise<OAuthCredentials> {
  const integrationService = container.resolve(IntegrationService);
  const credentials = await integrationService.getCredentials(tenantId, 'gmail');

  if (credentials?.clientId && credentials?.clientSecret) {
    return {
      clientId: credentials.clientId,
      clientSecret: credentials.clientSecret,
      source: 'integration',
    };
  }

  const { GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET } = getEnv();

  if (!GOOGLE_CLIENT_ID || !GOOGLE_CLIENT_SECRET) {
    throw new Error(
      'OAuth credentials not found. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET, ' +
      'or store them on the tenant integration.'
    );
  }

  return {
    clientId: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET,
    source: 'environment',
  };
}

/**
 * `customSession` puts tenantId on the session at run time, but better-auth's
 * inferred type does not carry it (better-auth#3888, noted in auth/better-auth.ts).
 * One narrow accessor, rather than casting the whole session and losing the rest of
 * its typing.
 */
function sessionTenantId(session: { user: { id: string; tenantId?: unknown } }): string | null {
  const value = session.user.tenantId;
  return typeof value === 'string' && value.length > 0 ? value : null;
}

/**
 * The `users` row id behind the session's identity.
 *
 * better-auth ids and `users.id` are different id spaces: `better_auth_user.id` is
 * TEXT and generated by better-auth, while every audit column here is a uuid —
 * `integrations.created_by` is `uuid` and joins to `users.id`. Handing the first to
 * the second makes Postgres reject the insert outright, which surfaces as a failed
 * connection AFTER the user has authorized at Google.
 *
 * This used to arrive as a `userId` query parameter, which was the wrong id space
 * and the caller's to choose: a signed-in user could name a colleague as whoever
 * connected the mailbox. It is resolved from the session here instead, the same way
 * tenantResolutionMiddleware does it.
 */
async function sessionUserId(email: string, tenantId: string): Promise<string | undefined> {
  const db = container.resolve<Database>('Database');

  const rows = await db
    .select({ id: users.id })
    .from(users)
    .where(and(eq(users.email, email), eq(users.tenantId, tenantId)))
    .limit(1);

  return rows[0]?.id;
}

/** Both endpoints must build the same redirect_uri or Google rejects the exchange. */
function getRedirectUri(): string {
  return `${getEnv().SERVICE_API_URL}/oauth/gmail/callback`;
}

/**
 * Where the user lands when the flow ends. `/integrations` is a `<Navigate replace>`
 * to the settings page that drops the query string, so link the real route directly
 * or the outcome is silently discarded.
 */
function webResultUrl(params: Record<string, string>): string {
  const query = new URLSearchParams({ tab: 'integrations', ...params });
  return `${getEnv().WEB_URL}/settings?${query.toString()}`;
}

/**
 * Initiate OAuth flow
 * GET /oauth/gmail/authorize?tenantId=xxx&userId=xxx
 *
 * This generates an authorization URL and redirects the user to Google's consent screen.
 * After authorization, Google will redirect back to /oauth/gmail/callback
 */
app.get('/gmail/authorize', async (c) => {
  // The tenant comes from the caller's own session, never from the URL.
  //
  // It used to be a query parameter on an unauthenticated route (this router is
  // mounted above every auth middleware), which meant a link could aim somebody
  // else's consent at a tenant of the sender's choosing: the victim sees Google's
  // real consent screen on Google's real domain, authorizes their own mailbox, and
  // the callback files the refresh token — and the initial 30-day sync — under the
  // attacker's tenant. Signing the state fixed who minted it, not who may act for
  // the tenant inside it.
  const session = await auth.api.getSession({ headers: c.req.raw.headers });

  if (!session) {
    // Not webResultUrl: /settings is behind ProtectedRoute, so a toast saying
    // "please sign in" would only ever be read by someone who just had to.
    // Send them to sign in and back to where they were instead.
    const next = encodeURIComponent('/settings?tab=integrations');
    return c.redirect(`${getEnv().WEB_URL}/login?next=${next}`);
  }

  const tenantId = sessionTenantId(session);

  if (!tenantId) {
    logger.error({ userId: session.user.id }, 'Session has no tenant; cannot start OAuth');
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'no-tenant',
      error: 'Your account is not linked to a workspace yet. Please contact support.',
    }));
  }

  // The web app still sends tenantId. Honour it only as an assertion to check, so a
  // crafted link disagreeing with the session is refused rather than silently
  // resolved to the session's tenant.
  const requestedTenantId = c.req.query('tenantId');

  if (requestedTenantId && requestedTenantId !== tenantId) {
    logger.warn(
      { sessionTenantId: tenantId, requestedTenantId, userId: session.user.id },
      'Refused OAuth authorize for a tenant the session does not own'
    );
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'tenant-mismatch',
      error: 'That connection request was for a different workspace. Please try again from Settings.',
    }));
  }

  try {
    const userId = await sessionUserId(session.user.email, tenantId);
    const { clientId, clientSecret, source } = await resolveOAuthCredentials(tenantId);
    const redirectUri = getRedirectUri();

    const oAuth2Client = new google.auth.OAuth2(clientId, clientSecret, redirectUri);

    // Signed, self-contained CSRF token. Nothing about this request is retained
    // in the process — see ./state.ts for why.
    const state = signOAuthState({ tenantId, userId });

    const authUrl = oAuth2Client.generateAuthUrl({
      access_type: 'offline',
      scope: GMAIL_SCOPE_URLS,
      prompt: 'consent', // Force consent to get refresh token
      state,
    });

    logger.info({ tenantId, redirectUri, credentialSource: source }, 'OAuth authorization initiated');

    // Redirect user to Google's consent screen
    return c.redirect(authUrl);
  } catch (error: any) {
    // The detail stays in the logs whoever is calling: these messages name
    // environment variables, and a caller has no use for them either way.
    logger.error({ error, tenantId }, 'Failed to initiate OAuth flow');
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'setup-failed',
      error: 'Gmail could not be connected right now. Please try again or contact support.',
    }));
  }
});

/**
 * OAuth callback endpoint
 * GET /oauth/gmail/callback?code=xxx&state=xxx
 *
 * Google redirects here after user authorizes.
 * We exchange the authorization code for tokens and save the refresh token.
 */
app.get('/gmail/callback', async (c) => {
  const code = c.req.query('code');
  const state = c.req.query('state');
  const error = c.req.query('error');

  // Handle authorization errors.
  //
  // This used to interpolate `error` into an HTML page. The value is whatever the
  // caller puts in the query string, `c.html` escapes nothing, and the page was
  // served from the crm-api origin — which is BETTER_AUTH_URL, so the session
  // cookies live there too. Anyone could hand a victim a link that ran script
  // against their session. Nothing reflects that value into markup now; the user
  // goes back to the app with a reason we chose.
  if (error) {
    logger.warn({ error }, 'OAuth authorization failed at Google');

    // Declining consent is a decision, not a fault, and it is the failure users
    // reach most often. It used to dead-end on an unstyled page with no way back.
    const declined = error === 'access_denied';

    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: declined ? 'denied' : 'google-error',
      error: declined
        ? 'Gmail was not connected because access was declined.'
        : 'Google could not complete the connection. Please try again.',
    }));
  }

  if (!code || !state) {
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'invalid',
      error: 'This connection request was incomplete. Please start again from Settings.',
    }));
  }

  // Verify state to prevent CSRF. A stale consent screen and a forged request are
  // reported separately: only the first is fixed by pressing the button again, and
  // rendering them identically is what made this failure unreadable.
  const verified = verifyOAuthState(state);

  if (verified.status === 'expired') {
    logger.warn(
      { ageSeconds: verified.ageSeconds, ttlSeconds: OAUTH_STATE_TTL_SECONDS },
      'OAuth state expired before the callback'
    );
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'expired',
      error: `This connection request expired after ${Math.round(OAUTH_STATE_TTL_SECONDS / 60)} minutes. Please connect Gmail again.`,
    }));
  }

  if (verified.status === 'invalid') {
    logger.error({ reason: verified.reason }, 'Rejected OAuth state');
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'invalid',
      error: 'This connection request could not be verified. Please start again from Settings.',
    }));
  }

  const { tenantId, userId } = verified.state;

  try {
    const integrationService = container.resolve(IntegrationService);

    // Same credentials and same redirect_uri as /authorize built, or Google
    // rejects the exchange.
    const { clientId, clientSecret } = await resolveOAuthCredentials(tenantId);
    const redirectUri = getRedirectUri();

    const oAuth2Client = new google.auth.OAuth2(
      clientId,
      clientSecret,
      redirectUri
    );

    // Exchange authorization code for tokens
    const { tokens } = await oAuth2Client.getToken(code);

    if (!tokens.refresh_token) {
      throw new Error(
        'No refresh token received. The user may need to revoke access first: ' +
        'https://myaccount.google.com/permissions'
      );
    }

    logger.info(
      {
        tenantId,
        scope: tokens.scope,
        hasRefreshToken: !!tokens.refresh_token
      },
      'OAuth tokens received'
    );

    // Set credentials first, then get user's email from Google
    oAuth2Client.setCredentials(tokens);
    const oauth2 = google.oauth2({ version: 'v2', auth: oAuth2Client });
    const { data: userInfo } = await oauth2.userinfo.get();
    const email = userInfo.email;

    if (!email) {
      throw new Error('Could not retrieve email from Google account');
    }

    logger.info({ tenantId, email }, 'Retrieved user email from Google');

    // Create or update integration based on email
    // Note: clientId and clientSecret are NOT stored in DB - they come from environment variables
    await integrationService.createOrUpdate({
      tenantId,
      authType: 'oauth',
      keys: {
        email,
        refreshToken: tokens.refresh_token,
        accessToken: tokens.access_token || undefined,
      },
      createdBy: userId,
    });

    logger.info({ tenantId, email }, 'OAuth integration created/updated successfully');

    // Auto-add tenant domains to blacklist to prevent collecting internal emails
    await integrationService.ensureTenantDomainsBlacklisted(tenantId, 'gmail');

    // Setup Gmail watch automatically
    try {
      const gmailServiceUrl = getEnv().SERVICE_GMAIL_URL;
      const watchResponse = await internalFetch(`${gmailServiceUrl}/api/watch?tenantId=${tenantId}`, {
        method: 'POST',
      });

      if (watchResponse.ok) {
        const watchData = await watchResponse.json();
        logger.info(
          { tenantId, watchExpiresAt: watchData.watchExpiresAt },
          'Gmail watch set up successfully after OAuth'
        );
      } else {
        const errorText = await watchResponse.text();
        logger.warn(
          { tenantId, status: watchResponse.status, error: errorText },
          'Failed to set up Gmail watch after OAuth - will need manual setup'
        );
      }
    } catch (watchError: any) {
      logger.warn(
        { tenantId, error: watchError.message },
        'Failed to set up Gmail watch after OAuth - will need manual setup'
      );
      // Don't fail the OAuth flow if watch setup fails
    }

    // Trigger initial sync to fetch historical emails (last 30 days)
    try {
      const gmailServiceUrl = getEnv().SERVICE_GMAIL_URL;
      const syncResponse = await internalFetch(`${gmailServiceUrl}/api/sync/${tenantId}/initial`, {
        method: 'POST',
      });

      if (syncResponse.ok) {
        const syncData = await syncResponse.json();
        logger.info(
          { tenantId, runId: syncData.runId },
          'Initial email sync triggered after OAuth'
        );
      } else {
        const errorText = await syncResponse.text();
        logger.warn(
          { tenantId, status: syncResponse.status, error: errorText },
          'Failed to trigger initial sync after OAuth'
        );
      }
    } catch (syncError: any) {
      logger.warn(
        { tenantId, error: syncError.message },
        'Failed to trigger initial sync after OAuth'
      );
      // Don't fail the OAuth flow if sync fails - user can manually trigger
    }

    // Redirect to web app integrations settings
    return c.redirect(webResultUrl({ oauth: 'success' }));
  } catch (error: any) {
    logger.error({ error, tenantId }, 'Failed to complete OAuth flow');

    // Redirect to web app with error
    return c.redirect(webResultUrl({
      oauth: 'error',
      reason: 'exchange-failed',
      error: error.message || 'Unknown error',
    }));
  }
});

export default app;
