import model from './model.json';

/**
 * A cheap gate in front of the LLM.
 *
 * 96.4% of stored mail is neutral, and every one of those costs a model call to
 * establish. This scores a message with a linear model distilled from 26,641
 * emails the LLM already judged, and lets the obvious neutrals be dropped
 * before any call is made.
 *
 * It is a SCREEN, not a rater. Measured on a temporal hold-out — trained on
 * older mail, tested on newer, which is what deployment actually faces —
 * sending the top-scoring 60% to the LLM retains 94% of its negatives and 94%
 * of the emails a human later wrote a resolution for. Sending 50% retains
 * ~89%. It cannot decide sentiment on its own: at a threshold strict enough to
 * be precise it finds about one complaint in ten.
 *
 * Deliberately not a second opinion. Anything it keeps still goes to the model
 * and the model's verdict stands; the only thing this changes is what never
 * gets asked.
 *
 * The weights live in model.json, exported from scikit-learn. This file must
 * reproduce that pipeline's arithmetic exactly or the threshold means nothing —
 * `score.test.ts` asserts parity against vectors generated by the Python side.
 */

interface PrefilterModel {
  version: string;
  trainedOn: { rows: number; negatives: number; upTo: string };
  intercept: number;
  threshold: number;
  /** term -> [idf, coefficient] */
  terms: Record<string, [number, number]>;
}

// Through `unknown`: TypeScript widens the imported JSON's [idf, coef] pairs to
// number[], which is not assignable to the tuple. The parity test is what
// actually guards this shape.
const M = model as unknown as PrefilterModel;

/** Mirrors TfidfVectorizer(strip_accents='unicode', lowercase=True). */
function normalize(text: string): string {
  return text
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase();
}

/**
 * scikit-learn's default token_pattern, `(?u)\b\w\w+\b`: runs of two or more
 * word characters. Single letters are dropped, which is why "a" and "I" never
 * appear in the vocabulary.
 */
function tokenize(text: string): string[] {
  return text.match(/[\p{L}\p{N}_]{2,}/gu) ?? [];
}

/** Unigrams and bigrams, matching ngram_range=(1, 2). */
function ngrams(tokens: string[]): string[] {
  const out: string[] = [...tokens];
  for (let i = 0; i + 1 < tokens.length; i++) out.push(`${tokens[i]} ${tokens[i + 1]}`);
  return out;
}

/**
 * The same body preparation the training data went through. Any divergence here
 * shifts every score, so it is kept deliberately simple and duplicated in the
 * Python exporter rather than shared through a config.
 */
export function prepare(subject: string | null, body: string | null): string {
  const raw = `${subject ?? ''} \n ${body ?? ''}`;
  const text = raw
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .split(/On .{0,200}?\bwrote:/)[0]
    .replace(/\s+/g, ' ')
    .trim();
  return text.slice(0, 3000);
}

/**
 * Log-odds that the LLM would call this negative. Higher means more suspicious.
 *
 * Reproduces sublinear_tf (1 + ln(count)), the fitted idf, and L2 normalisation
 * over the FULL feature space. The last point is the subtle one: the vector is
 * normalised using every in-vocabulary term, then only the 5,000 retained terms
 * contribute to the dot product. Normalising over the retained terms alone
 * would rescale every score and silently move the threshold.
 */
export function score(text: string): number {
  const counts = new Map<string, number>();
  for (const g of ngrams(tokenize(normalize(text)))) {
    counts.set(g, (counts.get(g) ?? 0) + 1);
  }
  if (counts.size === 0) return M.intercept;

  let norm = 0;
  const weighted: Array<[number, number]> = [];
  for (const [term, n] of counts) {
    const entry = M.terms[term];
    if (!entry) continue;
    const [idf, coef] = entry;
    const tfidf = (1 + Math.log(n)) * idf;
    norm += tfidf * tfidf;
    weighted.push([tfidf, coef]);
  }
  if (norm === 0) return M.intercept;

  const inv = 1 / Math.sqrt(norm);
  let dot = M.intercept;
  for (const [tfidf, coef] of weighted) dot += tfidf * inv * coef;
  return dot;
}

/**
 * "This is not the first time I have asked."
 *
 * The one thing a bag of words cannot see in a twelve-word email. Reading the
 * complaints this gate dropped, the pattern was unmistakable — "3rd follow up
 * on the email below", "I provide this info over and over", "they have raised
 * the same questions again". Repeated ignored follow-ups are named in the
 * sentiment prompt as a negative indicator, and they arrive in the shortest
 * messages in the corpus, which is precisely where a linear model over tf-idf
 * has nothing to weigh.
 *
 * Measured on the hold-out: fires on 0.3% of mail, 32% of which is labelled
 * negative — roughly a hundred times the base rate. Adding it lifts recall from
 * 94% to 96% while the share of mail sent to the LLM stays at 60%, because 28
 * messages in 8,881 is a rounding error in the budget.
 */
const CHASING =
  /\b(\d(?:st|nd|rd|th)\s+(?:follow[- ]?up|reminder)|follow(?:ing)?[- ]?up\s+again|again\s+on\s+(?:this|the below)|still (?:waiting|have not|haven'?t|no response)|over and over|repeatedly|as per my (?:last|previous)|third time|second time|chasing this)\b/i;

/**
 * Should this message be sent to the LLM?
 *
 * Fails OPEN: anything unscoreable goes to the model. A gate that silently
 * drops mail it could not parse would turn a parser bug into missing
 * escalations, and a missed complaint is far more expensive than a spent call.
 */
export function shouldAnalyze(subject: string | null, body: string | null): boolean {
  const text = prepare(subject, body);
  if (text.length < 25) return true;
  if (CHASING.test(text)) return true;
  return score(text) >= M.threshold;
}

export const prefilterMeta = {
  version: M.version,
  threshold: M.threshold,
  terms: Object.keys(M.terms).length,
  trainedOn: M.trainedOn,
};
